blank_issues_enabled: true
contact_links:
  - name: FAQ
    url: https://www.range42.net/faq/
    about: Please find our Frequently Asked Questions here.
  - name: Community Support
    url: https://github.com/orgs/range42/discussions
    about: For Community Support reach out here.
